name: Nightly

on:
  workflow_dispatch:
  repository_dispatch:
    types: [nightly-linux]

env:
  DYNAWO_VERSION: 1.7.0

jobs:
  fedora:
    name: Linux Fedora (${{ matrix.build-type }})
    runs-on: ubuntu-latest
    container: dynawo/dynawo-ci-nightly-fedora:latest
    strategy:
      matrix:
        build-type: [Release, Debug]
      fail-fast: false
    env:
      DYNAWO_RESULTS_SHOW: "false"
      DYNAWO_BUILD_TYPE: ${{ matrix.build-type }}
      DYNAWO_NB_PROCESSORS_USED: 2
      DYNAWO_FORCE_CXX11_ABI: "true"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Fetch Dynawo
        run: curl -LOs https://github.com/${{ github.repository_owner }}/dynawo/releases/download/nightly/Dynawo_omc_v$DYNAWO_VERSION.zip

      - name: Unzip Dynawo
        run: |
          unzip -qq "Dynawo_omc_v${DYNAWO_VERSION}.zip"

      - name: Dynawo version
        run: ./dynawo/dynawo.sh version

      - name: Build
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh build

      - name: Tests
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          dnf install -y gtest-devel gmock-devel
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh build-tests

      - name: NRT
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh nrt
