name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * 1-5'

jobs:
  fedora:
    name: Linux Fedora (${{ matrix.build-type }})
    runs-on: ubuntu-latest
    container: dynawo/dynawo-ci-nightly-fedora:latest
    strategy:
      matrix:
        build-type: [Release, Debug]
      fail-fast: false
    env:
      DYNAWO_RESULTS_SHOW: "false"
      DYNAWO_BUILD_TYPE: ${{ matrix.build-type }}
      DYNAWO_NB_PROCESSORS_USED: 2
      DYNAWO_FORCE_CXX11_ABI: "true"
      DYNAWO_VERSION: 1.5.0
      GH_API_DYNAWO: ${{ github.api_url }}/repos/${{ github.repository_owner }}/dynawo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CURL_JSON: 'curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --header "Content-Type: application/json"'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Fetch Dynawo
        run: |
          source .github/workflows/tools.sh
          download_asset $GH_API_DYNAWO nightly Dynawo_omc_V${DYNAWO_VERSION}.zip $GITHUB_TOKEN

      - name: Unzip Dynawo
        run: |
          unzip "Dynawo_omc_V${DYNAWO_VERSION}.zip"

      - name: Dynawo version
        run: ./dynawo/dynawo.sh version

      - name: Build
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh build

      - name: Tests
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          dnf install -y gtest-devel gmock-devel
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh build-tests

      - name: NRT
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)
          util/envDynawoAlgorithms.sh nrt
